### ISSUE TITLE
Cannot Update Registration / Edit Password for User

### ISSUE THREAD

**Issue by ThinkADRIAN** [gonzalo-bulnes/simple_token_authentication#172]
I am attempting to use the following command to edit the password for a user:
```
curl -X "PUT" "http://localhost:3000/" \
	-H "X-Rails-User-Email: test-12@thrivesync.com" \
	-H "X-Rails-User-Token: Kk11mLFwgsYcyefHkwrE" \
	-H "Content-Type: application/json" \
	-H "Accept: application/json" \
	-d $'{
  "rails_user": 
  {
	"password": "Password123",
	"password_confirmation": "Password123",
	"current_password": "Password1234"
  }
}'
```

However I get:
```
{"error":"You need to sign in or sign up before continuing."}
```

Here are my code samples:

Routes.rb
```
Rails.application.routes.draw do
  
  devise_for :rails_users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:registrations => 'my_devise/registrations',
    :omniauth_callbacks => "omniauth_callbacks", :sessions => 'rails_users/sessions', :passwords => 'rails_users/passwords'}
  match '/rails_users/:id/finish_signup' => 'rails_users#finish_signup', via: [:get, :patch], :as => :finish_signup
...
```

Registrations_Controller.rb
```
class MyDevise::RegistrationsController < Devise::RegistrationsController
  acts_as_token_authentication_handler_for RailsUser

  before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:update]

	def create
    super
	end

	def update
		super
  end

	def destroy
		super
	end

	private
	
	# Never trust parameters from the scary internet, only allow the white list through.
  def rails_user_params
    params.require(:rails_user).permit(:first_name, :last_name, :email, :password)
  end

	protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
  		u.permit(:first_name, :last_name, :email, :password, :password_confirmation, roles: [])
		end
  end

  # You can put the params you want to permit in the empty array.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) do |u|
  		u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, roles: [])
		end
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end
```

**Comment by ThinkADRIAN** [comment]
Found the resolution https://github.com/gonzalo-bulnes/simple_token_authentication/issues/36

**Comment by gonzalo-bulnes** [comment]
Hi @ThinkADRIAN, I'm glad you found the answer you were looking for in the FAQ, thanks for your feedback! Regards!

**Comment by ThinkADRIAN** [comment]
This enabled JSON request to work.  But broke Web request to edit the registration.  Web version now redirects to / with the follow Flash Message:

"You are already signed in."

```
Started GET "/edit" for 127.0.0.1 at 2015-05-29 18:34:31 -0400
Processing by MyDevise::RegistrationsController#edit as HTML
  RailsUser Load (0.5ms)  SELECT  "rails_users".* FROM "rails_users"  WHERE "rails_users"."id" = 1  ORDER BY "rails_users"."id" ASC LIMIT 1
Redirected to http://localhost:3000/
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 4ms (ActiveRecord: 0.5ms)
```

**Comment by ThinkADRIAN** [comment]
FYI - I can get web working again by commenting out the following code:

```
  prepend_before_filter :require_no_authentication, only: [ :new, :create, :edit, :update, :cancel ]
  prepend_before_filter :authenticate_scope!, only: [:destroy]
  acts_as_token_authentication_handler_for RailsUser

  # Disable token authentication for all actions
  # See https://github.com/gonzalo-bulnes/simple_token_authentication/blob/master/lib/simple_token_authentication/acts_as_token_authentication_handler.rb#L12-L15
  skip_before_filter :authenticate_rails_user_from_token!
  skip_before_filter :authenticate_rails_user!

  # Enable token authentication only for the :update, :destroy actions
  before_filter :authenticate_rails_user_from_token!, :only => [:update, :destroy]
  before_filter :authenticate_rails_user!, :only => [:update, :destroy]
```
But commenting this code out breaks JSON request.

**Comment by gonzalo-bulnes** [comment]
Hi @ThinkADRIAN,

I may be missing a few things, but could the following be what you're intending to do?

```ruby
acts_as_token_authentication_handler_for RailsUser, only: [:update, :destroy]
```

**Comment by ThinkADRIAN** [comment]
Hi @gonzalo-bulnes,

I want all actions to work with token authentication.  This works.  

However, it breaks my navbar link to the edit registration web page.  Instead of going to the Edit Page, it redirects to / with Flash Message: You are already signed in.

**Comment by ThinkADRIAN** [comment]
Resolved this issue by creating a proper API with registrations controller.

**Comment by gonzalo-bulnes** [comment]
Hi @ThinkADRIAN,

I couldn't answer to you sooner, but was about to suggest you some options to decouple the token-related and Devise-related aspects of your _rails users_ authentication :

**1.** If token authentication is only used by API users, see #155

```ruby
# Enable token authentication for API users (JSON requests),
# but do not enable the Devise-related authentication strategies
acts_as_token_authentication_handler_for RailsUser, fallback_to_devise: false,
  if: lambda{ |controller| controller.request.format.json? }

# Enable the Devise strategies for webapp users
before_filter :authenticate_rails_user!, unless: lambda{ |controller| controller.request.format.json? } 
```

**2.** If token authentication is used with both JSON and HTML requests

```ruby
# What we want to prevent is the 'You are already signed in' message from Devise.

# Enable token authentication for all actions
acts_as_token_authentication_handler_for RailsUser, fallback_to_devise: false

# Do attempt other authentication strategies unless token authentication was successful
before_filter :authenticate_rails_user!, unless: lambda { |controller| controller.current_user.presence }
```

Of course, separating the API and webapp controllers as you did is another option to configure both authentication aspects in a (drastically?) decoupled way. Please note that now that you have separated both concerns, I recommend you to disable the Devise fallback (`fallback_to_devise: false`) in your API controllers (this is particularly important if you later disable the CSRF protection, see the warning in the [documentation][doc] and [this discussion](https://github.com/gonzalo-bulnes/simple_token_authentication/issues/49#issuecomment-43422690) for details).

  [doc]: https://github.com/gonzalo-bulnes/simple_token_authentication#allow-controllers-to-handle-token-authentication

By the way, if you wanted to post a gist with your API `RegistrationsController`, I'm sure it would be of great help for others developers ; )

Have a nice weekend!

**Comment by ThinkADRIAN** [comment]
Thanks @gonzalo-bulnes for the detailed response!

Here's the gist for the API Registrations Controller:
https://gist.github.com/ThinkADRIAN/cda5cd33f207f9cd8959

**Comment by gonzalo-bulnes** [comment]
:+1: !

**Comment by qx** [comment]
edit password still not work ,is there a simple way to fix it?

**Comment by gonzalo-bulnes** [comment]
Hello @qx, what do you mean by "still not work"?

Can you provide more details? This [wiki article](https://github.com/gonzalo-bulnes/simple_token_authentication/wiki/Asking-for-help) explains what information is necessary for others to help you troubleshooting your _Simple Token Authentication_ setup.
